version: "3.8"
services:
  app:
    build: .
    container_name: compass
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:mysql://compass.cz0cuiamu64l.ap-northeast-2.rds.amazonaws.com:3306/compass-db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
    restart: unless-stopped